name: Build STM32 Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install ARM toolchain
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi make

      - name: Build firmware
        working-directory: src
        run: |
          make

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: teslacharger-bin
          path: Firmware/build/*.bin

  release:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: teslacharger-bin

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          name: Firmware Build ${{ github.sha }}
          files: "*.bin"
